### ISSUE TITLE
Statistic service does not discover all nodes in the network.

### ISSUE THREAD

**Issue by Wayonb** [symbol/statistics-service#120]
Currently Statistics service query always start with the nodes in the config.  These nodes should only be used for the first query when the DB is empty.  Using the nodes in the DB, this allow the service to discover the entire network

https://github.com/symbol/statistics-service/blob/d78a50c920d8334bbdbb55acc1ed48c4880788fc/src/services/NodeMonitor.ts#L87

The other option is the service will need to loop until it discover all nodes.

**Comment by yilmazbahadir** [comment]
Just checked the code, it is initially calling `node/peers` API endpoint on the static node list provided (as config) and then running a nested `node/peers` call round on the node list gathered from the first calls. And yet missing some nodes in the network as you pointed out.

I think, currently, we have `1307` nodes in `mainnet`.

1. Regarding your first suggestion, in the second round that I mentioned above, we'll have 1307 nodes at hand to call `node/peers`. Not sure how long it will take to get the peer list from each and then call `node/info` endpoints on each, so this option will probably need some optimization. A little bit info about how nodes find `peers` in `catapult-server` might be very insightful.
2. For option 2, if it'll be in loops then each iteration will depend on the previous one and should be continued until no new nodes found.
Both of the options would be costly timewise. Should be done in a distributed fashion, I believe.

**Comment by AnthonyLaw** [comment]
IMO, I will go for the first option, I believe it will shorter time than option 2.

To discover nodes, we just need a `node/peers` endpoint.
